runtime: php55
api_version: 1

handlers:
- url: /.*
  script: index.php

env_variables:
  # Replace project, instance, database, user and password with the values obtained
  # when configuring your Cloud SQL instance.
  MYSQL_DSN: mysql:unix_socket=/cloudsql/involuted-bird-185511:us-central1:scautosys;dbname=sc_autosys
  MYSQL_USER: root
  MYSQL_PASSWORD: 'SC#p@ssw0rd#db#'
